version: "3.4"
services:
  web:
    build: .
    container_name: revealeit.njk.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cavity.rule=Host(`revealeit.njk.localhost`)"
      - "traefik.http.routers.cavity.tls=true"
      - "traefik.docker.network=proxy"
    networks:
      - default
      - proxy
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true

networks:
  proxy:
    external: true
